#!/bin/bash

echo "> Build variables:"
build_date="$(date +"%Y-%m-%d %T")"
echo ">> Build Date: $build_date"
vcs_ref="$(git rev-parse HEAD)"
echo ">> VCS Ref: $vcs_ref"
version=$(cat version_file)
echo ">> Version: $version"

# Available variables: https://docs.docker.com/docker-hub/builds/advanced/
echo ">> Source Commit: $SOURCE_COMMIT"
echo ">> Source Branch: $SOURCE_BRANCH"
echo ">> Docker Repo: $DOCKER_REPO"
echo ">> Image Name: $IMAGE_NAME"

echo "> Run docker build"
docker build \
  --build-arg BUILD_DATE="$build_date" \
  --build-arg VCS_REF="$SOURCE_COMMIT" \
  --build-arg BUILD_VERSION="$version" \
  --build-arg SOURCE_BRANCH="$SOURCE_BRANCH" \
  --build-arg SOURCE_REPOSITORY_URL="$SOURCE_REPOSITORY_URL" \
  --tag "$IMAGE_NAME" \
  .
